module.exports = {
    name: 'motivate',
    aliases: ['mt', 'cheerup', 'cu'],
    description: 'Sends words of encouragement with a single command.',
    async execute(whatsapp, message) {
        const motivation = [
  "You're doing great!",
  "Keep up the good work!",
  "Believe in yourself!",
  "You are capable of amazing things!",
  "Stay positive and positive things will happen.",
  "Every day is a second chance.",
  "You've got this!",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Your hard work will pay off.",
  "Don't stop when you're tired. Stop when you're done.",
  "The best way to predict the future is to create it.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "Believe in your dreams.",
  "Your time is now.",
  "The only limit is your mind.",
  "You are stronger than you think.",
  "Focus on the journey, not the destination.",
  "Dream big and dare to fail.",
  "You are capable of more than you know.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "You are your only limit.",
  "Hard times may have held you down, but they will not last forever.",
  "One day or day one. You decide.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are amazing and don't you forget it.",
  "You are stronger than your challenges.",
  "Turn your wounds into wisdom.",
  "Make it happen. Shock everyone.",
  "Every morning brings new potential.",
  "You are capable of changing the world.",
  "Your potential is endless.",
  "You are a diamond; resilient and unbreakable.",
  "The road may be tough, but the destination is worth it.",
  "Your journey is your own; own it.",
  "You are the master of your fate.",
  "Every accomplishment starts with the decision to try.",
  "Chase your dreams relentlessly.",
  "Don't be afraid to start over; it's a brand new opportunity to rebuild what you truly want.",
  "You are the creator of your destiny.",
  "Stay focused, stay positive, and never give up.",
  "Believe you can, and you're halfway there.",
  "Don't let yesterday take up too much of today.",
  "The only way to do great work is to love what you do.",
  "Your limitations—it's all in your mind.",
  "You are capable of greatness.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You are stronger than your excuses.",
  "Life is short; make it amazing.",
  "You are not alone on this journey.",
  "Believe in yourself, even when no one else does.",
  "Your potential is endless.",
  "Your success is only a matter of time.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "You are unique, and that is your power.",
  "Success is not the key to happiness; happiness is the key to success.",
  "Your time is limited, so don't waste it living someone else's life.",
  "You are enough just as you are.",
  "The best revenge is massive success.",
  "Dream it. Believe it. Achieve it.",
  "Your journey matters; make it amazing.",
  "You are the architect of your life; build it your way.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Your potential has no limits.",
  "The only way to do great work is to love what you do.",
  "You are in charge of your own destiny.",
  "The best way to predict the future is to create it.",
  "You have the power to create the life you desire.",
  "Success is not in what you have but who you are.",
  "Your dreams are worth the chase.",
  "You have the strength to overcome any challenge.",
  "Believe in yourself, and you will be unstoppable.",
  "You have the courage to face whatever comes your way.",
  "The journey to your dreams may be tough, but it's worth it.",
  "You are stronger than any obstacle.",
  "You are one of a kind, and that is your superpower.",
  "Your dreams are your ticket to the stars. Climb aboard and launch.",
  "Believe in your potential and nothing can hold you back.",
  "You are more powerful than you know; you are beautiful just as you are.",
  "With each new day comes new opportunities.",
  "You are the author of your life story.",
  "Success is a journey, not a destination.",
  "You have the fire within to achieve greatness.",
  "Believe in your dreams, and they may come true. Believe in yourself, and they will come true.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The best is yet to come.",
  "Your dreams are within reach.",
  "Success is the sum of small efforts repeated daily.",
  "Your potential is boundless.",
  "Believe in yourself, and others will too.",
  "Your dreams are within reach.",
  "You have the courage to overcome any obstacle.",
  "Stay focused on your goals, and you will succeed.",
  "Your journey is just beginning.",
  "The best is yet to come.",
  "You are on the path to greatness.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Your hard work will pay off.",
  "Don't stop when you're tired. Stop when you're done.",
  "The best way to predict the future is to create it.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "Believe in your dreams.",
  "Your time is now.",
  "The only limit is your mind.",
  "You are stronger than you think.",
  "Focus on the journey, not the destination.",
  "Dream big and dare to fail.",
  "You are capable of more than you know.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "You are your only limit.",
  "Hard times may have held you down, but they will not last forever.",
  "One day or day one. You decide.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are amazing and don't you forget it.",
  "You are stronger than your challenges.",
  "Turn your wounds into wisdom.",
  "Make it happen. Shock everyone.",
  "Every morning brings new potential.",
  "You are capable of changing the world.",
  "Your potential is endless.",
  "You are a diamond; resilient and unbreakable.",
  "The road may be tough, but the destination is worth it.",
  "Your journey is your own; own it.",
  "You are the master of your fate.",
  "Every accomplishment starts with the decision to try.",
  "Chase your dreams relentlessly.",
  "Don't be afraid to start over; it's a brand new opportunity to rebuild what you truly want.",
  "You are the creator of your destiny.",
  "Stay focused, stay positive, and never give up.",
  "Believe you can, and you're halfway there.",
  "Don't let yesterday take up too much of today.",
  "The only way to do great work is to love what you do.",
  "Your limitations—it's all in your mind.",
  "You are capable of greatness.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You are stronger than your excuses.",
  "Life is short; make it amazing.",
  "You are not alone on this journey.",
  "Believe in yourself, even when no one else does.",
  "Your potential is endless.",
  "Your success is only a matter of time.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "You are unique, and that is your power.",
  "Success is not the key to happiness; happiness is the key to success.",
  "Your time is limited, so don't waste it living someone else's life.",
  "You are enough just as you are.",
  "The best revenge is massive success.",
  "Dream it. Believe it. Achieve it.",
  "Your journey matters; make it amazing.",
  "You are the architect of your life; build it your way.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Your potential has no limits.",
  "The only way to do great work is to love what you do.",
  "You are in charge of your own destiny.",
  "The best way to predict the future is to create it.",
  "You have the power to create the life you desire.",
  "Success is not in what you have but who you are.",
  "Your dreams are worth the chase.",
  "You have the strength to overcome any challenge.",
  "Believe in yourself, and you will be unstoppable.",
  "You have the courage to face whatever comes your way.",
  "The journey to your dreams may be tough, but it's worth it.",
  "You are stronger than any obstacle.",
  "You are one of a kind, and that is your superpower.",
  "Your dreams are your ticket to the stars. Climb aboard and launch.",
  "Believe in your potential and nothing can hold you back.",
  "You are more powerful than you know; you are beautiful just as you are.",
  "With each new day comes new opportunities.",
  "You are the author of your life story.",
  "Success is a journey, not a destination.",
  "You have the fire within to achieve greatness.",
  "Believe in your dreams, and they may come true. Believe in yourself, and they will come true.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The best is yet to come.",
  "Your dreams are within reach.",
  "Success is the sum of small efforts repeated daily.",
  "Your potential is boundless.",
  "Believe in yourself, and others will too.",
  "Your dreams are within reach.",
  "You have the courage to overcome any obstacle.",
  "Stay focused on your goals, and you will succeed.",
  "Your journey is just beginning.",
  "The best is yet to come.",
  "You are on the path to greatness.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Your hard work will pay off.",
  "Don't stop when you're tired. Stop when you're done.",
  "The best way to predict the future is to create it.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "Believe in your dreams.",
  "Your time is now.",
  "The only limit is your mind.",
  "You are stronger than you think.",
  "Focus on the journey, not the destination.",
  "Dream big and dare to fail.",
  "You are capable of more than you know.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "You are your only limit.",
  "Hard times may have held you down, but they will not last forever.",
  "One day or day one. You decide.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are amazing and don't you forget it.",
  "You are stronger than your challenges.",
  "Turn your wounds into wisdom.",
  "Make it happen. Shock everyone.",
  "Every morning brings new potential.",
  "You are capable of changing the world.",
  "Your potential is endless.",
  "You are a diamond; resilient and unbreakable.",
  "The road may be tough, but the destination is worth it.",
  "Your journey is your own; own it.",
  "You are the master of your fate.",
  "Every accomplishment starts with the decision to try.",
  "Chase your dreams relentlessly.",
  "Don't be afraid to start over; it's a brand new opportunity to rebuild what you truly want.",
  "You are the creator of your destiny.",
  "Stay focused, stay positive, and never give up.",
  "Believe you can, and you're halfway there.",
  "Don't let yesterday take up too much of today.",
  "The only way to do great work is to love what you do.",
  "Your limitations—it's all in your mind.",
  "You are capable of greatness.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You are stronger than your excuses.",
  "Life is short; make it amazing.",
  "You are not alone on this journey.",
  "Believe in yourself, even when no one else does.",
  "Your potential is endless.",
  "Your success is only a matter of time.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "You are unique, and that is your power.",
  "Success is not the key to happiness; happiness is the key to success.",
  "Your time is limited, so don't waste it living someone else's life.",
  "You are enough just as you are.",
  "The best revenge is massive success.",
  "Dream it. Believe it. Achieve it.",
  "Your journey matters; make it amazing.",
  "You are the architect of your life; build it your way.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Your potential has no limits.",
  "The only way to do great work is to love what you do.",
  "You are in charge of your own destiny.",
  "The best way to predict the future is to create it.",
  "You have the power to create the life you desire.",
  "Success is not in what you have but who you are.",
  "Your dreams are worth the chase.",
  "You have the strength to overcome any challenge.",
  "Believe in yourself, and you will be unstoppable.",
  "You have the courage to face whatever comes your way.",
  "The journey to your dreams may be tough, but it's worth it.",
  "You are stronger than any obstacle.",
  "You are one of a kind, and that is your superpower.",
  "Your dreams are your ticket to the stars. Climb aboard and launch.",
  "Believe in your potential and nothing can hold you back.",
  "You are more powerful than you know; you are beautiful just as you are.",
  "With each new day comes new opportunities.",
  "You are the author of your life story.",
  "Success is a journey, not a destination.",
  "You have the fire within to achieve greatness.",
  "Believe in your dreams, and they may come true. Believe in yourself, and they will come true.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The best is yet to come.",
  "Your dreams are within reach.",
  "Success is the sum of small efforts repeated daily.",
  "Your potential is boundless.",
  "Believe in yourself, and others will too.",
  "Your dreams are within reach.",
  "You have the courage to overcome any obstacle.",
  "Stay focused on your goals, and you will succeed.",
  "Your journey is just beginning.",
  "The best is yet to come.",
  "You are on the path to greatness.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Your hard work will pay off.",
  "Don't stop when you're tired. Stop when you're done.",
  "The best way to predict the future is to create it.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "Believe in your dreams.",
  "Your time is now.",
  "The only limit is your mind.",
  "You are stronger than you think.",
  "Focus on the journey, not the destination.",
  "Dream big and dare to fail.",
  "You are capable of more than you know.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "You are your only limit.",
  "Hard times may have held you down, but they will not last forever.",
  "One day or day one. You decide.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are amazing and don't you forget it.",
  "You are stronger than your challenges.",
  "Turn your wounds into wisdom.",
  "Make it happen. Shock everyone.",
  "Every morning brings new potential.",
  "You are capable of changing the world.",
  "Your potential is endless.",
  "You are a diamond; resilient and unbreakable.",
  "The road may be tough, but the destination is worth it.",
  "Your journey is your own; own it.",
  "You are the master of your fate.",
  "Every accomplishment starts with the decision to try.",
  "Chase your dreams relentlessly.",
  "Don't be afraid to start over; it's a brand new opportunity to rebuild what you truly want.",
  "You are the creator of your destiny.",
  "Stay focused, stay positive, and never give up.",
  "Believe you can, and you're halfway there.",
  "Don't let yesterday take up too much of today.",
  "The only way to do great work is to love what you do.",
  "Your limitations—it's all in your mind.",
  "You are capable of greatness.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You are stronger than your excuses.",
  "Life is short; make it amazing.",
  "You are not alone on this journey.",
  "Believe in yourself, even when no one else does.",
  "Your potential is endless.",
  "Your success is only a matter of time.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "You are unique, and that is your power.",
  "Success is not the key to happiness; happiness is the key to success.",
  "Your time is limited, so don't waste it living someone else's life.",
  "You are enough just as you are.",
  "The best revenge is massive success.",
  "Dream it. Believe it. Achieve it.",
  "Your journey matters; make it amazing.",
  "You are the architect of your life; build it your way.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Your potential has no limits.",
  "The only way to do great work is to love what you do.",
  "You are in charge of your own destiny.",
  "The best way to predict the future is to create it.",
  "You have the power to create the life you desire.",
  "Success is not in what you have but who you are.",
  "Your dreams are worth the chase.",
  "You have the strength to overcome any challenge.",
  "Believe in yourself, and you will be unstoppable.",
  "You have the courage to face whatever comes your way.",
  "The journey to your dreams may be tough, but it's worth it.",
  "You are stronger than any obstacle.",
  "You are one of a kind, and that is your superpower.",
  "Your dreams are your ticket to the stars. Climb aboard and launch.",
  "Believe in your potential and nothing can hold you back.",
  "You are more powerful than you know; you are beautiful just as you are.",
  "With each new day comes new opportunities.",
  "You are the author of your life story.",
  "Success is a journey, not a destination.",
  "You have the fire within to achieve greatness.",
  "Believe in your dreams, and they may come true. Believe in yourself, and they will come true.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The best is yet to come.",
  "Your dreams are within reach.",
  "Success is the sum of small efforts repeated daily.",
  "Your potential is boundless.",
  "Believe in yourself, and others will too.",
  "Your dreams are within reach.",
  "You have the courage to overcome any obstacle.",
  "Stay focused on your goals, and you will succeed.",
  "Your journey is just beginning.",
  "The best is yet to come.",
  "You are on the path to greatness.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Your hard work will pay off.",
  "Don't stop when you're tired. Stop when you're done.",
  "The best way to predict the future is to create it.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "Believe in your dreams.",
  "Your time is now.",
  "The only limit is your mind.",
  "You are stronger than you think.",
  "Focus on the journey, not the destination.",
  "Dream big and dare to fail.",
  "You are capable of more than you know.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "You are your only limit.",
  "Hard times may have held you down, but they will not last forever.",
  "One day or day one. You decide.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are amazing and don't you forget it.",
  "You are stronger than your challenges.",
  "Turn your wounds into wisdom.",
  "Make it happen. Shock everyone.",
  "Every morning brings new potential.",
  "You are capable of changing the world.",
  "Your potential is endless.",
  "You are a diamond; resilient and unbreakable.",
  "The road may be tough, but the destination is worth it.",
  "Your journey is your own; own it.",
  "You are the master of your fate.",
  "Every accomplishment starts with the decision to try.",
  "Chase your dreams relentlessly.",
  "Don't be afraid to start over; it's a brand new opportunity to rebuild what you truly want.",
  "You are the creator of your destiny.",
  "Stay focused, stay positive, and never give up.",
  "Believe you can, and you're halfway there.",
  "Don't let yesterday take up too much of today.",
  "The only way to do great work is to love what you do.",
  "Your limitations—it's all in your mind.",
  "You are capable of greatness.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You are stronger than your excuses.",
  "Life is short; make it amazing.",
  "You are not alone on this journey.",
  "Believe in yourself, even when no one else does.",
  "Your potential is endless.",
  "Your success is only a matter of time.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "You are unique, and that is your power.",
  "Success is not the key to happiness; happiness is the key to success.",
  "Your time is limited, so don't waste it living someone else's life.",
  "You are enough just as you are.",
  "The best revenge is massive success.",
  "Dream it. Believe it. Achieve it.",
  "Your journey matters; make it amazing.",
  "You are the architect of your life; build it your way.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Your potential has no limits.",
  "The only way to do great work is to love what you do.",
  "You are in charge of your own destiny.",
  "The best way to predict the future is to create it.",
  "You have the power to create the life you desire.",
  "Success is not in what you have but who you are.",
  "Your dreams are worth the chase.",
  "You have the strength to overcome any challenge.",
  "Believe in yourself, and you will be unstoppable.",
  "You have the courage to face whatever comes your way.",
  "The journey to your dreams may be tough, but it's worth it.",
  "You are stronger than any obstacle.",
  "You are one of a kind, and that is your superpower.",
  "Your dreams are your ticket to the stars. Climb aboard and launch.",
  "Believe in your potential and nothing can hold you back.",
  "You are more powerful than you know; you are beautiful just as you are.",
  "With each new day comes new opportunities.",
  "You are the author of your life story.",
  "Success is a journey, not a destination.",
  "You have the fire within to achieve greatness.",
  "Believe in your dreams, and they may come true. Believe in yourself, and they will come true.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The best is yet to come.",
  "Your dreams are within reach.",
  "Success is the sum of small efforts repeated daily.",
  "Your potential is boundless.",
  "Believe in yourself, and others will too.",
  "Your dreams are within reach.",
  "You have the courage to overcome any obstacle.",
  "Stay focused on your goals, and you will succeed.",
  "Your journey is just beginning.",
  "The best is yet to come.",
  "You are on the path to greatness.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Your hard work will pay off.",
  "Don't stop when you're tired. Stop when you're done.",
  "The best way to predict the future is to create it.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "Believe in your dreams.",
  "Your time is now.",
  "The only limit is your mind.",
  "You are stronger than you think.",
  "Focus on the journey, not the destination.",
  "Dream big and dare to fail.",
  "You are capable of more than you know.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "You are your only limit.",
  "Hard times may have held you down, but they will not last forever.",
  "One day or day one. You decide.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "You are amazing and don't you forget it.",
  "You are stronger than your challenges.",
  "Turn your wounds into wisdom.",
  "Make it happen. Shock everyone.",
  "Every morning brings new potential.",
  "You are capable of changing the world.",
  "Your potential is endless.",
  "You are a diamond; resilient and unbreakable.",
  "The road may be tough, but the destination is worth it.",
  "Your journey is your own; own it.",
  "You are the master of your fate.",
  "Every accomplishment starts with the decision to try.",
  "Chase your dreams relentlessly.",
  "Don't be afraid to start over; it's a brand new opportunity to rebuild what you truly want.",
  "You are the creator of your destiny.",
  "Stay focused, stay positive, and never give up.",
  "Believe you can, and you're halfway there.",
  "Don't let yesterday take up too much of today.",
  "The only way to do great work is to love what you do.",
  "Your limitations—it's all in your mind.",
  "You are capable of greatness.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You are stronger than your excuses.",
  "Life is short; make it amazing.",
  "You are not alone on this journey.",
  "Believe in yourself, even when no one else does.",
  "Your potential is endless.",
  "Your success is only a matter of time.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "You are unique, and that is your power.",
  "Success is not the key to happiness; happiness is the key to success.",
  "Your time is limited, so don't waste it living someone else's life.",
  "You are enough just as you are.",
  "The best revenge is massive success.",
  "Dream it. Believe it. Achieve it.",
  "Your journey matters; make it amazing.",
  "You are the architect of your life; build it your way.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Your potential has no limits.",
  "The only way to do great work is to love what you do.",
  "You are in charge of your own destiny.",
  "The best way to predict the future is to create it.",
  "You have the power to create the life you desire.",
  "Success is not in what you have but who you are.",
  "Your dreams are worth the chase.",
  "You have the strength to overcome any challenge.",
  "Believe in yourself, and you will be unstoppable.",
  "You have the courage to face whatever comes your way.",
  "The journey to your dreams may be tough, but it's worth it.",
  "You are stronger than any obstacle.",
  "You are one of a kind, and that is your superpower.",
  "Your dreams are your ticket to the stars. Climb aboard and launch.",
  "Believe in your potential and nothing can hold you back.",
  "You are more powerful than you know; you are beautiful just as you are.",
  "With each new day comes new opportunities.",
  "You are the author of your life story.",
  "Success is a journey, not a destination.",
  "You have the fire within to achieve greatness.",
  "Believe in your dreams, and they may come true. Believe in yourself, and they will come true.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The best is yet to come.",
  "Your dreams are within reach.",
  "Success is the sum of small efforts repeated daily.",
  "Your potential is boundless.",
  "Believe in yourself, and others will too.",
  "Your dreams are within reach.",
  "You have the courage to overcome any obstacle.",
  "Stay focused on your goals, and you will succeed.",
  "Your journey is just beginning.",
  "The best is yet to come.",
  "You are on the path to greatness."
        ];

        const contact = await message.getContact();
        const senderName = contact.pushname || 'Unknown';
        const randomIndex = Math.floor(Math.random() * motivation.length);
        const randomMotivation = motivation[randomIndex];

        await whatsapp.sendMessage(message.from, `*Cheer up! ${senderName}*\n\n*${randomMotivation}*`, {
            quotedMessage: message
        });
    }
};

